{
 "title": "Fraud Detection Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Frauds in last 10 min",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) FILTER (WHERE is_fraud = TRUE) AS \"total_fraud_count\"\nFROM\n  transactions\nWHERE\n  transaction_time >= NOW() - INTERVAL '10 minutes';"
    }
   ]
  },
  {
   "title": "Fraud Count per 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1m', transaction_time) AS \"10min\",\n  COUNT(*) AS \"fraud_count\"\nFROM\n  transactions\nWHERE\n  is_fraud = TRUE\nGROUP BY\n  time_bucket('1m', transaction_time)\nORDER BY\n  \"10min\" DESC;\n"
    }
   ]
  },
  {
   "title": "Total Fraud Percentage in 10 min",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) FILTER (WHERE is_fraud = TRUE) * 100.0 / NULLIF(COUNT(*), 0) AS \"fraud_percentage\"\nFROM\n  transactions\nWHERE\n  transaction_time >= NOW() - INTERVAL '10 minutes';\n\n"
    }
   ]
  },
  {
   "title": "Fraud rate per Transaction Type",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  transaction_method,\n  COUNT(*) FILTER (WHERE is_fraud = TRUE) * 100.0 / COUNT(*) AS \"fraud_rate\"\nFROM\n  transactions\nWHERE transaction_time >= NOW() - INTERVAL '10 minutes'\nGROUP BY\n  transaction_method\nORDER BY\n  fraud_rate DESC;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  location AS \"country\",\n  COUNT(*) AS \"fraud_count\"\nFROM\n  transactions\nWHERE\n  is_fraud = TRUE\n  AND transaction_time >= NOW() - INTERVAL '10 minutes'\nGROUP BY\n  location\nORDER BY\n  fraud_count DESC;"
    }
   ]
  },
  {
   "title": "Fraud Transactions Per country",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), location FROM transactions WHERE is_fraud = true and transaction_time >= NOW() - INTERVAL '10 minutes' GROUP BY location "
    }
   ]
  },
  {
   "title": "Recent Fraud Transactions",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  transaction_id,\n  transaction_amount,\n  location,\n  transaction_method,\n  transaction_time\nFROM\n  transactions\nWHERE\n  is_fraud = TRUE\nORDER BY\n  transaction_id DESC\nLIMIT 100;"
    }
   ]
  }
 ]
}